export * from './ping.controller';
export * from './solicitud-persona.controller';
export * from './persona-solicitud.controller';
export * from './solicitud-avion.controller';
export * from './avion-persona.controller';
export * from './persona-avion.controller';
export * from './persona.controller';
export * from './solicitud.controller';
export * from './avion.controller';
